#PostgreSQL configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
    show-sql: true
    open-in-view: false